name: bazzite-custom
version: 44
cosign-version: none # This line disables the signing requirement

base-image: ghcr.io/ublue-os/bazzite-gnome
image-version: stable

modules:
  - type: files
    files:
      - from: files/usr/lib/udev/rules.d
        to: /usr/lib/udev/rules.d

  - type: akmods
    install:
      - hid-tmff2
